### ISSUE TITLE
Minor typo "knowlwedge"

### ISSUE THREAD

**Issue by AndrewCloete** [nuclia/nucliadb#1012]
**Describe the bug**
![image](https://github.com/nuclia/nucliadb/assets/10737709/ce73f5e1-1b04-4b4e-8a9f-25bc07dbf899)

**Comment by jotare** [comment]
Hi @AndrewCloete, do you want to contribute your typo fix? We're happy to have new contributors to NucliaDB!

**Comment by AndrewCloete** [comment]
Hi Joan,

Thanks for the message. Yeah, I would love to even though it is a tiny
change. I've rebased onto master and it included some commits. Would you
like me to undo that?

Kind regards
Andrew

**Comment by jotare** [comment]
No worries, open a PR with your branch and we can see it there :)
