### ISSUE TITLE
results = sdk.search(kbid=kb.uuid, vector=query_vectors, vectorset="base", min_score=0.25)

### ISSUE THREAD

**Issue by FB-wh** [nuclia/nucliadb#1293]
**Describe the bug**

**Steps to reproduce (if applicable)**

1.
2.

**Expected behavior**

**Configuration:**
Please provide:

1. Output of `pip list | grep nucliadb`

**Comment by FB-wh** [comment]
AttributeError: 'KnowledgeBox' object has no attribute 'uuid'

**Comment by FB-wh** [comment]
> 
Thank you, I changed "kd.uuid" to "kd.id" and it already works.

**Comment by FB-wh** [comment]
> hi @FB-wh I am afraid you are using an old version of the sdk.
> 
> I have tried reproducing this with the latest and I get no such bug.
> 
> ```python
> >> from nucliadb_sdk import NucliaDB
> >> sdk = NucliaDB()
> >> res = sdk.search(kbid="my-kbid", vector=[1.0], vectorset="base", min_score=0.25)
> >> len(res.resources)
> 8
> ```
> 
> Can you tell me what docs/examples were you following when you encountered this bug?



> hi @FB-wh I am afraid you are using an old version of the sdk.
> 
> I have tried reproducing this with the latest and I get no such bug.
> 
> ```python
> >> from nucliadb_sdk import NucliaDB
> >> sdk = NucliaDB()
> >> res = sdk.search(kbid="my-kbid", vector=[1.0], vectorset="base", min_score=0.25)
> >> len(res.resources)
> 8
> ```
> 
> Can you tell me what docs/examples were you following when you encountered this bug?

Thank you, I changed kd.uuid to kd.id and it already works

> hi @FB-wh I am afraid you are using an old version of the sdk.
> 
> I have tried reproducing this with the latest and I get no such bug.
> 
> ```python
> >> from nucliadb_sdk import NucliaDB
> >> sdk = NucliaDB()
> >> res = sdk.search(kbid="my-kbid", vector=[1.0], vectorset="base", min_score=0.25)
> >> len(res.resources)
> 8
> ```
> 
> Can you tell me what docs/examples were you following when you encountered this bug?

1. Thank you, I changed "kd.uuid" to "kd.id" and it works.

- [ ]

**Comment by FB-wh** [comment]
> hi @FB-wh I am afraid you are using an old version of the sdk.
> 
> I have tried reproducing this with the latest and I get no such bug.
> 
> ```python
> >> from nucliadb_sdk import NucliaDB
> >> sdk = NucliaDB()
> >> res = sdk.search(kbid="my-kbid", vector=[1.0], vectorset="base", min_score=0.25)
> >> len(res.resources)
> 8
> ```
> 
> Can you tell me what docs/examples were you following when you encountered this bug?


Thank you, I changed kd.uuid to kd.id and it already works

**Comment by FB-wh** [comment]
> hi @FB-wh I am afraid you are using an old version of the sdk.
> 
> I have tried reproducing this with the latest and I get no such bug.
> 
> ```python
> >> from nucliadb_sdk import NucliaDB
> >> sdk = NucliaDB()
> >> res = sdk.search(kbid="my-kbid", vector=[1.0], vectorset="base", min_score=0.25)
> >> len(res.resources)
> 8
> ```
> 
> Can you tell me what docs/examples were you following when you encountered this bug?

Hello, I am currently learning Nucliadb and I have tested the performance of the database. I have encountered a few questions:
1.Is it necessary to create a resource every time I insert a vector?
2.It takes 10 minutes to insert 10,000 vectors (each vector has 768 dimensions). Is this normal?
Here is the code:
```python
import tqdm
from nucliadb_sdk import get_or_create
import numpy as np

my_kb = get_or_create(slug="my_new_kb", nucliadb_base_url="http://localhost:8080")
count = 10_000
embeddings = [[np.random.random() for _ in range(768)] for _ in range(count)]

for i in tqdm.tqdm(range(10000)):
    resource_id = my_kb.upload(
        text=str(i),
        vectors={"base": embeddings[i]},
    )

**Comment by lferran** [comment]
Hi again @FB-wh !

Nuclia's goal is to make sense of unstructured data. Therefore, NucliaDB has been designed to store many vectors for the same document. Typically, we generate a vector for each different paragraph of the document.

A simple example would be the following:

```python
from nucliadb_sdk.vectors import Vector, Vectors
import tqdm
from nucliadb_sdk import get_or_create
import numpy as np
KB = "mykb"
URL = "http://localhost:8080"
PARAGRAPH_SEPARATOR = "\n\n"

PARAGRAPHS = [
    "The quick brown fox jumps over the lazy dog.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec odio.",
    "Sed auctor ipsum ut tellus faucibus, in aliquam augue aliquam.",
    "Fusce euismod, nisl eget mattis aliquam, diam odio aliquet magna, vitae.",
] * 250

TEXT = PARAGRAPH_SEPARATOR.join(PARAGRAPHS)

def compute_vectors(text) -> Vectors:
    vectors = []
    current_pos = 0
    paragraphs = text.split("\n\n")
    for par in paragraphs:
        v = Vector(
            value=[np.random.random() for _ in range(768)],
            vectorset="base",
            positions=(current_pos, current_pos + len(par)),
        )
        current_pos += len(PARAGRAPH_SEPARATOR)
        vectors.append(v)
    return vectors

my_kb = get_or_create(slug=KB, nucliadb_base_url=URL)

for i in tqdm.tqdm(range(10)):
    resource_id = my_kb.upload(
        text=TEXT,
        vectors=compute_vectors(TEXT),
    )

```
As you can see, each line of the text has its own vector. In that case, the observed throughput would be much higher than the one you see in your example. It took around 6 seconds to insert 10_000 vectors on my local machine.

On search time, only the individual paragraphs are retrieved.

Worth mentioning that we have plans to improve the api around custom vectors so that it is easier to work with.

**Comment by FB-wh** [comment]
Thank you very much! @lferran. I referred to your code, Inserting vectors is very fast.

I have another question, I use the inserted vector to query, and the score of the query result is not 1.

**Comment by lferran** [comment]
I've tried to search with the inserted vector and I get a value of `0.9999998807907104`.
It may have to do with the precision of the vector similarity function calculations. Just for me to understand: is this a problem for you in some way as a user of the database?
Most importantly is that you should get it as the first item on the list of results, no?

Anyhow, I will share it with the @nuclia/nuclia-db team! Thanks for taking the time to share some feedback :)
