### ISSUE TITLE
Python SDK - Uvicorn package pinned to extremely out of date version. 

### ISSUE THREAD

**Issue by chrisgoddard** [nuclia/nucliadb#2513]
Your python sdk is pinned to uvicorn<=0.19.0 which was released in October 2022 - this is really out of date and makes compatibility with other projects very difficult.

**Comment by jotare** [comment]
Hi @chrisgoddard, thanks for reporting this!

We'll unpin the dependency and release a nucliadb version in a week or two.

**Comment by lferran** [comment]
hi @chrisgoddard, are you installing nucliadb from pip?
Just wondering, what is your use case? let us know if you need any help!
