### ISSUE TITLE
[nucliadb_client] Passing api key in NucliaDBClient 

### ISSUE THREAD

**Issue by solodynamo** [nuclia/nucliadb#855]
**Describe the bug**
At current there seems to be no way to pass API KEY in NucliaDBClient. How do we pass this? 

Because of this there seems to an error:
`httpx.ConnectError: [Errno -2] Name or service not known`

**Steps to reproduce (if applicable)**

1. Initialise NucliaDBClient with host
2. Try to call any function like 
client = NucliaDBClient(host="abchost", grpc=8060, http=8081, train=8040)
 kb = client.get_kb(slug="demo-slug")
    

**Expected behavior**
There should be some way to authenticate using API key using the client.

**Comment by vangheem** [comment]
It looks like you're using the nucliadb_client package. That package is deprecated and should not be used anymore.

You're probably looking for the sdk usage. It's on our roadmap to improve the sdk capabilities and the documentation around this.

Here is a quickstart on how you can work with your knowledge box. You'll need the full url to the knowledge box for this approach and your API key.

```
from nucliadb_sdk.client import NucliaDBClient, FindRequest
client = NucliaDBClient(url="https://europe-1.nuclia.cloud/api/v1/kb/<kb id>", api_key="<api key here>")
lient.find(FindRequest(query="Who was president of United States During WWII?"))
```

**Comment by vangheem** [comment]
Closing this. `nucliadb_client` is deprecated. Let me know if you have any other questions!
